export type SongSearchResult = {
  id: string;
  groupKey?: string;
  groupingSource?: "groupedProjectId" | "fallback" | "both";
  versionCount?: number;
  groupedProjectIds?: number[];
  groupedProjectId?: number;
  artistId?: number;
  authorId?: number;
  isPreferredCharter?: boolean;
  title: string;
  artist?: string;
  album?: string;
  creator?: string;
  tuning?: string;
  tuningIds?: number[];
  parts?: string[];
  durationText?: string;
  durationSeconds?: number;
  year?: number;
  sourceUpdatedAt?: number;
  sourceId?: number;
  platforms?: string[];
  hasLyrics?: boolean;
  downloads?: number;
  source: string;
  sourceUrl?: string;
  score?: number;
};
