export type SongSearchResult = {
  id: string;
  groupedProjectId?: number;
  artistId?: number;
  authorId?: number;
  title: string;
  artist?: string;
  album?: string;
  creator?: string;
  tuning?: string;
  parts?: string[];
  durationText?: string;
  durationSeconds?: number;
  year?: number;
  sourceUpdatedAt?: number;
  sourceId?: number;
  platforms?: string[];
  hasLyrics?: boolean;
  downloads?: number;
  source: string;
  sourceUrl?: string;
  score?: number;
};
