export const tuningOptions = [
  "High F# Standard",
  "High F Standard",
  "E Standard",
  "Drop D",
  "Eb Standard",
  "Eb Drop Db",
  "D Standard",
  "D Drop C",
  "C# Standard",
  "C# Drop B",
  "C Standard",
  "C Drop Bb",
  "B Standard",
  "B Drop A",
  "Bb Standard",
  "Bb Drop Ab",
  "A Standard",
  "Ab Standard",
  "G Standard",
  "Low Gb Standard",
  "Low F Standard",
  "Octave",
  "Open A",
  "Open B",
  "Open C",
  "Open D",
  "Open E",
  "Open F",
  "Open G",
  "Celtic",
  "Other",
] as const;

export const pathOptions = ["lead", "rhythm", "bass", "voice"] as const;
