PRAGMA foreign_keys=OFF;

ALTER TABLE `channel_settings` RENAME TO `__old_channel_settings`;

CREATE TABLE `channel_settings` (
	`channel_id` text PRIMARY KEY NOT NULL,
	`bot_channel_enabled` integer DEFAULT false NOT NULL,
	`admin_force_bot_while_offline` integer DEFAULT false NOT NULL,
	`moderator_can_manage_requests` integer DEFAULT false NOT NULL,
	`moderator_can_manage_blacklist` integer DEFAULT false NOT NULL,
	`moderator_can_manage_setlist` integer DEFAULT false NOT NULL,
	`moderator_can_manage_vip_tokens` integer DEFAULT false NOT NULL,
	`moderator_can_manage_tags` integer DEFAULT false NOT NULL,
	`requests_enabled` integer DEFAULT true NOT NULL,
	`allow_anyone_to_request` integer DEFAULT true NOT NULL,
	`allow_subscribers_to_request` integer DEFAULT true NOT NULL,
	`allow_vips_to_request` integer DEFAULT true NOT NULL,
	`only_official_dlc` integer DEFAULT false NOT NULL,
	`allowed_tunings_json` text DEFAULT '[]' NOT NULL,
	`required_paths_json` text DEFAULT '[]' NOT NULL,
	`max_queue_size` integer DEFAULT 50 NOT NULL,
	`max_viewer_requests_at_once` integer DEFAULT 1 NOT NULL,
	`max_subscriber_requests_at_once` integer DEFAULT 1 NOT NULL,
	`max_vip_viewer_requests_at_once` integer DEFAULT 1 NOT NULL,
	`max_vip_subscriber_requests_at_once` integer DEFAULT 1 NOT NULL,
	`limit_regular_requests_enabled` integer DEFAULT false NOT NULL,
	`regular_requests_per_period` integer DEFAULT 1 NOT NULL,
	`regular_request_period_seconds` integer DEFAULT 0 NOT NULL,
	`limit_vip_requests_enabled` integer DEFAULT false NOT NULL,
	`vip_requests_per_period` integer DEFAULT 1 NOT NULL,
	`vip_request_period_seconds` integer DEFAULT 0 NOT NULL,
	`blacklist_enabled` integer DEFAULT false NOT NULL,
	`let_setlist_bypass_blacklist` integer DEFAULT false NOT NULL,
	`setlist_enabled` integer DEFAULT false NOT NULL,
	`subscribers_must_follow_setlist` integer DEFAULT false NOT NULL,
	`auto_grant_vip_token_to_subscribers` integer DEFAULT false NOT NULL,
	`duplicate_window_seconds` integer DEFAULT 900 NOT NULL,
	`overlay_access_token` text DEFAULT '' NOT NULL,
	`overlay_show_creator` integer DEFAULT false NOT NULL,
	`overlay_show_album` integer DEFAULT false NOT NULL,
	`overlay_animate_now_playing` integer DEFAULT true NOT NULL,
	`overlay_accent_color` text DEFAULT '#cf7cff' NOT NULL,
	`overlay_vip_color` text DEFAULT '#a855f7' NOT NULL,
	`overlay_text_color` text DEFAULT '#f5f7fb' NOT NULL,
	`overlay_muted_text_color` text DEFAULT '#9aa4b2' NOT NULL,
	`overlay_panel_color` text DEFAULT '#0f1117' NOT NULL,
	`overlay_background_color` text DEFAULT '#05070d' NOT NULL,
	`overlay_border_color` text DEFAULT '#2a3140' NOT NULL,
	`overlay_background_opacity` integer DEFAULT 0 NOT NULL,
	`overlay_corner_radius` integer DEFAULT 22 NOT NULL,
	`overlay_item_gap` integer DEFAULT 12 NOT NULL,
	`overlay_item_padding` integer DEFAULT 16 NOT NULL,
	`overlay_title_font_size` integer DEFAULT 26 NOT NULL,
	`overlay_meta_font_size` integer DEFAULT 14 NOT NULL,
	`command_prefix` text DEFAULT '!sr' NOT NULL,
	`updated_at` integer DEFAULT (unixepoch() * 1000) NOT NULL,
	`required_paths_match_mode` text NOT NULL DEFAULT 'any',
	`auto_grant_vip_tokens_to_sub_gifters` integer DEFAULT false NOT NULL,
	`auto_grant_vip_tokens_to_gift_recipients` integer DEFAULT false NOT NULL,
	`auto_grant_vip_tokens_for_cheers` integer DEFAULT false NOT NULL,
	`cheer_bits_per_vip_token` integer DEFAULT 200 NOT NULL,
	`cheer_minimum_token_percent` integer DEFAULT 25 NOT NULL,
	`moderator_can_manage_blocked_chatters` integer DEFAULT false NOT NULL,
	`moderator_can_view_vip_tokens` integer DEFAULT false NOT NULL,
	`show_playlist_positions` integer DEFAULT false NOT NULL,
	`auto_grant_vip_tokens_for_streamelements_tips` integer DEFAULT false NOT NULL,
	`streamelements_tip_amount_per_vip_token` real DEFAULT 5 NOT NULL,
	`streamelements_tip_webhook_token` text DEFAULT '' NOT NULL,
	`allow_request_path_modifiers` integer DEFAULT false NOT NULL,
	`auto_grant_vip_tokens_for_shared_sub_renewal_message` integer DEFAULT false NOT NULL,
	`auto_grant_vip_tokens_for_raiders` integer DEFAULT false NOT NULL,
	`raid_minimum_viewer_count` integer DEFAULT 1 NOT NULL,
	FOREIGN KEY (`channel_id`) REFERENCES `channels`(`id`) ON UPDATE no action ON DELETE no action
);

INSERT INTO `channel_settings` (
	`channel_id`,
	`bot_channel_enabled`,
	`admin_force_bot_while_offline`,
	`moderator_can_manage_requests`,
	`moderator_can_manage_blacklist`,
	`moderator_can_manage_setlist`,
	`moderator_can_manage_vip_tokens`,
	`moderator_can_manage_tags`,
	`requests_enabled`,
	`allow_anyone_to_request`,
	`allow_subscribers_to_request`,
	`allow_vips_to_request`,
	`only_official_dlc`,
	`allowed_tunings_json`,
	`required_paths_json`,
	`max_queue_size`,
	`max_viewer_requests_at_once`,
	`max_subscriber_requests_at_once`,
	`max_vip_viewer_requests_at_once`,
	`max_vip_subscriber_requests_at_once`,
	`limit_regular_requests_enabled`,
	`regular_requests_per_period`,
	`regular_request_period_seconds`,
	`limit_vip_requests_enabled`,
	`vip_requests_per_period`,
	`vip_request_period_seconds`,
	`blacklist_enabled`,
	`let_setlist_bypass_blacklist`,
	`setlist_enabled`,
	`subscribers_must_follow_setlist`,
	`auto_grant_vip_token_to_subscribers`,
	`duplicate_window_seconds`,
	`overlay_access_token`,
	`overlay_show_creator`,
	`overlay_show_album`,
	`overlay_animate_now_playing`,
	`overlay_accent_color`,
	`overlay_vip_color`,
	`overlay_text_color`,
	`overlay_muted_text_color`,
	`overlay_panel_color`,
	`overlay_background_color`,
	`overlay_border_color`,
	`overlay_background_opacity`,
	`overlay_corner_radius`,
	`overlay_item_gap`,
	`overlay_item_padding`,
	`overlay_title_font_size`,
	`overlay_meta_font_size`,
	`command_prefix`,
	`updated_at`,
	`required_paths_match_mode`,
	`auto_grant_vip_tokens_to_sub_gifters`,
	`auto_grant_vip_tokens_to_gift_recipients`,
	`auto_grant_vip_tokens_for_cheers`,
	`cheer_bits_per_vip_token`,
	`cheer_minimum_token_percent`,
	`moderator_can_manage_blocked_chatters`,
	`moderator_can_view_vip_tokens`,
	`show_playlist_positions`,
	`auto_grant_vip_tokens_for_streamelements_tips`,
	`streamelements_tip_amount_per_vip_token`,
	`streamelements_tip_webhook_token`,
	`allow_request_path_modifiers`,
	`auto_grant_vip_tokens_for_shared_sub_renewal_message`,
	`auto_grant_vip_tokens_for_raiders`,
	`raid_minimum_viewer_count`
)
SELECT
	`channel_id`,
	`bot_channel_enabled`,
	`admin_force_bot_while_offline`,
	`moderator_can_manage_requests`,
	`moderator_can_manage_blacklist`,
	`moderator_can_manage_setlist`,
	`moderator_can_manage_vip_tokens`,
	`moderator_can_manage_tags`,
	`requests_enabled`,
	`allow_anyone_to_request`,
	`allow_subscribers_to_request`,
	`allow_vips_to_request`,
	`only_official_dlc`,
	`allowed_tunings_json`,
	`required_paths_json`,
	`max_queue_size`,
	`max_viewer_requests_at_once`,
	`max_subscriber_requests_at_once`,
	`max_vip_viewer_requests_at_once`,
	`max_vip_subscriber_requests_at_once`,
	`limit_regular_requests_enabled`,
	`regular_requests_per_period`,
	`regular_request_period_seconds`,
	`limit_vip_requests_enabled`,
	`vip_requests_per_period`,
	`vip_request_period_seconds`,
	`blacklist_enabled`,
	`let_setlist_bypass_blacklist`,
	`setlist_enabled`,
	`subscribers_must_follow_setlist`,
	`auto_grant_vip_token_to_subscribers`,
	`duplicate_window_seconds`,
	`overlay_access_token`,
	`overlay_show_creator`,
	`overlay_show_album`,
	`overlay_animate_now_playing`,
	`overlay_accent_color`,
	`overlay_vip_color`,
	`overlay_text_color`,
	`overlay_muted_text_color`,
	`overlay_panel_color`,
	`overlay_background_color`,
	`overlay_border_color`,
	`overlay_background_opacity`,
	`overlay_corner_radius`,
	`overlay_item_gap`,
	`overlay_item_padding`,
	`overlay_title_font_size`,
	`overlay_meta_font_size`,
	`command_prefix`,
	`updated_at`,
	`required_paths_match_mode`,
	`auto_grant_vip_tokens_to_sub_gifters`,
	`auto_grant_vip_tokens_to_gift_recipients`,
	`auto_grant_vip_tokens_for_cheers`,
	`cheer_bits_per_vip_token`,
	`cheer_minimum_token_percent`,
	`moderator_can_manage_blocked_chatters`,
	`moderator_can_view_vip_tokens`,
	`show_playlist_positions`,
	`auto_grant_vip_tokens_for_streamelements_tips`,
	`streamelements_tip_amount_per_vip_token`,
	`streamelements_tip_webhook_token`,
	`allow_request_path_modifiers`,
	`auto_grant_vip_tokens_for_shared_sub_renewal_message`,
	`auto_grant_vip_tokens_for_raiders`,
	`raid_minimum_viewer_count`
FROM `__old_channel_settings`;

DROP TABLE `__old_channel_settings`;

PRAGMA foreign_keys=ON;
